---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

collections:
  - name: 'community.crypto'
    source: 'https://galaxy.ansible.com'

roles:
  - src: 'ansibleguy.infra_certs'
