---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

collections:
  - 'community.crypto'
  - 'community.general'

roles:
  - name: 'oxlorg.certs'
    src: 'git+https://github.com/O-X-L/ansible-role-certs'
