---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

collections:
  - name: 'community.crypto'
    source: 'https://galaxy.ansible.com'

roles:
  - src: 'https://github.com/ansibleguy/infra_certs.git'
    version: 'stable'
    name: 'ansibleguy.infra_certs'
