---

- name: Nginx | Certs | Generate Self-signed certificate (1/3)
  community.crypto.openssl_privatekey:
    path: "{{ NGINX_CERT_PUB_PATH }}/{{ NGINX_CERT_KEY_PATH }}"
    mode: 0444
    owner: "{{ NGINX_USER }}"
    group: "{{ NGINX_GROUP }}"

- name: Nginx | Certs | Generate Self-signed certificate (2/3)
  community.crypto.openssl_csr:
    path: "{{ NGINX_CERT_PUB_PATH }}/{{ NGINX_CERT_CSR_FILE }}"
    privatekey_path: "{{ NGINX_CERT_PUB_PATH }}/{{ NGINX_CERT_KEY_PATH }}"
    country_name: "{{ NGINX_CERT_CSR_OPTIONS.country }}"
    organization_name: "{{ NGINX_CERT_CSR_OPTIONS.org }}"
    email_address: "{{ NGINX_CERT_CSR_OPTIONS.email }}"
    common_name: "{{ NGINX_CERT_CSR_OPTIONS.cn }}"
    subject_alt_name: "DNS:{{ NGINX_DOMAIN }}{% if NGINX_IP != '' %},IP:{{ NGINX_IP }}{% endif %}{% for alias in NGINX_ALIASES %},DNS:{{ alias }}{% endfor %}"

- name: Nginx | Certs | Generate Self-signed certificate (3/3)
  community.crypto.x509_certificate:
    path: "{{ nginx_cert_path }}/certs/{{ nginx_cert_pub_file }}"
    privatekey_path: "{{ NGINX_CERT_PUB_PATH }}/{{ NGINX_CERT_KEY_PATH }}"
    csr_path: "{{ NGINX_CERT_PUB_PATH }}/{{ NGINX_CERT_CSR_FILE }}"
    provider: selfsigned
    valid_in: 3650d
    mode: 0444
    owner: "{{ NGINX_USER }}"
    group: "{{ NGINX_GROUP }}"
