---

- name: Nginx | Certs | SelfSigned | Installing dependencies
  ansible.builtin.apt:
    pkg: ['python3-cryptography']

- name: Nginx | Certs | SelfSigned | Generate Self-signed certificate (1/3)
  community.crypto.openssl_privatekey:
    path: "{{ NGINX_CERT_KEY_PATH }}/{{ NGINX_CERT_KEY_FILE }}"
    mode: 0444

- name: Nginx | Certs | SelfSigned | Generate Self-signed certificate (2/3)
  community.crypto.openssl_csr:
    path: "{{ NGINX_CERT_PUB_PATH }}/{{ NGINX_CERT_CSR_FILE }}"
    privatekey_path: "{{ NGINX_CERT_KEY_PATH }}/{{ NGINX_CERT_KEY_FILE }}"
    country_name: "{{ NGINX_CERT_CSR_DATA.country }}"
    organization_name: "{{ NGINX_CERT_CSR_DATA.org }}"
    email_address: "{{ NGINX_CERT_CSR_DATA.email }}"
    common_name: "{{ NGINX_CERT_CSR_DATA.cn }}"
    subject_alt_name: "DNS:{{ NGINX_DOMAIN }}{% if NGINX_IP != '' %},IP:{{ NGINX_IP }}{% endif %}{% for alias in NGINX_ALIASES %},DNS:{{ alias }}{% endfor %}"

- name: Nginx | Certs | SelfSigned | Generate Self-signed certificate (3/3)
  community.crypto.x509_certificate:
    path: "{{ NGINX_CERT_PUB_PATH }}/{{ NGINX_CERT_PUB_FILE }}"
    privatekey_path: "{{ NGINX_CERT_KEY_PATH }}/{{ NGINX_CERT_KEY_FILE }}"
    csr_path: "{{ NGINX_CERT_PUB_PATH }}/{{ NGINX_CERT_CSR_FILE }}"
    provider: selfsigned
    valid_in: 3650d
    mode: 0444
