---

- name: Nginx | Installing nginx
  ansible.builtin.apt:
    pkg: ['nginx']

- name: Nginx | Configuring certificates
  ansible.builtin.import_tasks: certs.yml

- name: Nginx | Adding site config
  ansible.builtin.template:
    src: 'templates/etc/nginx/sites-available/site.j2'
    dest: "/etc/nginx/sites-available/site_{{ nginx_domain }}"
  register: site_config

- name: Nginx | Enabling site config
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/site_{{ nginx_domain }}"
    dest: "/etc/nginx/sites-enabled/site_{{ nginx_domain }}"
    state: link
  register: site_state

- name: Nginx | Enabling nginx service
  ansible.builtin.systemd:
    name: 'nginx.service'
    enabled: yes
    state: started

- name: Nginx | Restarting nginx service
  ansible.builtin.systemd:
    name: 'nginx.service'
    state: restarted
  when: site_config.changed or site_state.changed
