---

- name: Nginx | Checking config
  ansible.builtin.assert:
    that:
      - nginx is defined
      - nginx.sites is defined
      - nginx.sites | length > 0
  tags: always

- name: Nginx | Processing debian config
  ansible.builtin.import_tasks: debian/main.yml
  when: "ansible_distribution|lower in ['debian', 'ubuntu']"
