---

# NOTE: stop from reload/restart when config is invalid
- name: Validate-nginx-config
  ansible.builtin.command: 'nginx -t -c /etc/nginx/nginx.conf'
  changed_when: false

- name: Reload-nginx
  ansible.builtin.systemd:
    name: 'nginx.service'
    state: reloaded

- name: Restart-nginx
  ansible.builtin.systemd:
    name: 'nginx.service'
    state: restarted
