---

- name: Converge
  hosts: test-ag-nginx-tester
  vars:
    dummy_ssl:
      mode: 'snakeoil'
      cert:
        cn: 'Nginx'
        org: 'AnsibleGuy Test'
        email: 'testmaster@oxl.at'
    dummy_backend:
      ip: '127.0.0.1'
      port: 8080

    nginx:
      sites:
        TESTproxy:
          domain: 'nginx1.test.oxl.at'
          ssl: "{{ dummy_ssl }}"
          mode: 'proxy'
          proxy: "{{ dummy_backend }}"

        TEST_basicauth:
          domain: 'nginx2.test.oxl.at'
          ssl: "{{ dummy_ssl }}"
          proxy: "{{ dummy_backend }}"

          basic_auth:
            enable: true
            provider: 'file'
            file:
              users:
                someguy: 'somepassword'

        TEST_noplain:
          domain: 'nginx3.test.oxl.at'
          plain_site: false
          ssl: "{{ dummy_ssl }}"
          proxy: "{{ dummy_backend }}"

        TESTserver:
          domain: 'nginx4.test.oxl.at'
          ssl: "{{ dummy_ssl }}"
          mode: 'server'
          server:
            path: '/var/www/test4'
            index: ['test.html']

        TESTredirect:
          domain: 'nginx5.test.oxl.at'
          ssl: "{{ dummy_ssl }}"
          mode: 'redirect'
          redirect:
            target: 'https://github.com/O-X-L'

        TESTsecurity:
          domain: 'nginx6.test.oxl.at'
          ssl: "{{ dummy_ssl }}"
          mode: 'server'
          server:
            path: '/var/www/test6'
            index: ['test.html']
          security:
            allow_only_methods: ['GET', 'HEAD']
            block_script_bots: true
            block_bad_crawler_bots: true

  roles:
    - oxlorg.nginx
