---

- name: Converge
  hosts: test-ag-nginx-tester
  vars:
    dummy_ssl:
      mode: 'ca'
      cert:
        cn: 'Nginx'
        org: 'AnsibleGuy Test'
        email: 'testmaster@ansibleguy.net'
    dummy_backend:
      ip: '127.0.0.1'
      port: 8080

    nginx:
      sites:
        TESTproxy:
          domain: 'nginx1.test.ansibleguy.net'
          ssl: "{{ dummy_ssl }}"
          mode: 'proxy'
          proxy: "{{ dummy_backend }}"

        TEST_basicauth:
          domain: 'nginx2.test.ansibleguy.net'
          ssl: "{{ dummy_ssl }}"
          proxy: "{{ dummy_backend }}"

          basic_auth:
            enable: true
            provider: 'file'
            file:
              users:
                someguy: 'somepassword'

        TEST_noplain:
          domain: 'nginx3.test.ansibleguy.net'
          plain_site: false
          ssl: "{{ dummy_ssl }}"
          proxy: "{{ dummy_backend }}"

        TESTserver:
          domain: 'nginx4.test.ansibleguy.net'
          ssl: "{{ dummy_ssl }}"
          mode: 'server'
          server:
            path: '/var/www/test4'
            index: ['test.html']

        TESTredirect:
          domain: 'nginx5.test.ansibleguy.net'
          ssl: "{{ dummy_ssl }}"
          mode: 'redirect'
          redirect:
            target: 'https://github.com/ansibleguy'

  roles:
    - ansibleguy.infra_nginx
