---

- name: "Nginx | Debian | Site '{{ name }}' | Checking config"
  ansible.builtin.fail:
    msg: "The required site-configuration was not provided!
    Needed: 'domain'"
  when: site.domain is undefined

- name: "Nginx | Debian | Site '{{ name }}' | Processing local certs"
  ansible.builtin.import_tasks: add_certs.yml
  when: "site.ssl.mode in ['selfsigned', 'existing', 'ca']"
  tags: [certs, sites]

- name: "Nginx | Debian | Site '{{ name }}' | Adding site config"
  ansible.builtin.template:
    src: 'templates/etc/nginx/sites-available/site.j2'
    dest: "/etc/nginx/sites-available/site_{{ name }}"
  tags: [config, sites]

- name: "Nginx | Debian | Site '{{ name }}' | Enabling site config"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/site_{{ name }}"
    dest: "/etc/nginx/sites-enabled/site_{{ name }}"
    state: link
  tags: [config, sites]
