---

- name: Nginx | Debian | Status page | Adding site config
  ansible.builtin.template:
    src: 'templates/etc/nginx/sites-available/status.j2'
    dest: '/etc/nginx/sites-available/status'
    mode: 0640
    owner: 'root'
    group: "{{ NGINX_CONFIG.group }}"
  tags: [config, sites, base]

- name: Nginx | Debian | Status page | Enabling site config
  ansible.builtin.file:
    src: '/etc/nginx/sites-available/status'
    dest: '/etc/nginx/sites-enabled/status'
    state: link
  tags: [config, sites, base]
