---

- name: "Nginx | Debian | Site {{ name }} | Certs | SelfSigned | Installing dependencies"
  ansible.builtin.apt:
    pkg: ['python3-cryptography']
  tags: [certs, sites]

- name: "Nginx | Debian | Site {{ name }} | Certs | SelfSigned | Generate Self-signed certificate (1/3)"
  community.crypto.openssl_privatekey:
    path: "{{ local_cert_key }}"
    mode: 0444
  tags: [certs, sites]

- name: "Nginx | Debian | Site {{ name }} | Certs | SelfSigned | Generate Self-signed certificate (2/3)"
  community.crypto.openssl_csr:
    path: "{{ local_cert_csr }}"
    privatekey_path: "{{ local_cert_key }}"
    country_name: "{{ site.ssl.csr_data.country }}"
    organization_name: "{{ site.ssl.csr_data.org }}"
    email_address: "{{ site.ssl.csr_data.email }}"
    common_name: "{{ site.ssl.csr_data.cn }}"
    subject_alt_name: "DNS:{{ site.domain }}{% if site.ip is not none %},IP:{{ site.ip }}{% endif %}{% for alias in site.aliases %},DNS:{{ alias }}{% endfor %}"
  tags: [certs, sites]

- name: "Nginx | Debian | Site {{ name }} | Certs | SelfSigned | Generate Self-signed certificate (3/3)"
  community.crypto.x509_certificate:
    path: "{{ local_cert_pub }}"
    privatekey_path: "{{ local_cert_key }}"
    csr_path: "{{ local_cert_csr }}"
    provider: selfsigned
    valid_in: 3650d
    mode: 0444
  tags: [certs, sites]
