---

- name: "Nginx | Debian | Site {{ name }} | Certs | Local | Checking if cert pub exists"
  ansible.builtin.stat:
    path: "{{ site.ssl.file_pub }}"
  register: exists_cert_pub
  tags: [certs, sites]

- name: "Nginx | Debian | Site {{ name }} | Certs | Local | Checking if cert pk exists"
  ansible.builtin.stat:
    path: "{{ site.ssl.file_key }}"
  register: exists_cert_key
  tags: [certs, sites]

- name: "Nginx | Debian | Site {{ name }} | Certs | Local | Creating public directory"
  ansible.builtin.file:
    path: "{{ site.ssl.file_pub | dirname }}"
    state: directory
    mode: 0755
  when: not exists_cert_pub.stat.exists
  tags: [certs, sites]

- name: "Nginx | Debian | Site {{ name }} | Certs | Local | Creating private directory"
  ansible.builtin.file:
    path: "{{ site.ssl.file_key | dirname }}"
    state: directory
    mode: 0750
    group: "{% if 'ssl-cert' in groups %}ssl-cert{% else %}{{ NGINX_CONFIG.group }}{% endif %}"
  when: not exists_cert_key.stat.exists
  tags: [certs, sites]

- name: "Nginx | Debian | Site {{ name }} | Certs | Local | Allowing service-user to read certificate (if needed)"
  ansible.builtin.user:
    name: "{{ NGINX_CONFIG.user }}"
    groups: 'ssl-cert'
    append: yes
  when:
    - not exists_cert_key.stat.exists
    - "'ssl-cert' in groups"
  tags: [certs, sites]

- name: "Nginx | Debian | Site {{ name }} | Certs | Local | Creating selfsigned certificates"
  ansible.builtin.import_tasks: add_certs_selfsigned.yml
  when: >
    site.ssl.mode == 'self-signed' and
    (not exists_cert_key.stat.exists or
    not exists_cert_pub.stat.exists) and
    ((copy_cert_pub.failed is defined and copy_cert_pub.failed) or
    (copy_cert_key.failed is defined and copy_cert_key.failed))
  tags: [certs, sites]

- name: "Nginx | Debian | Site {{ name }} | Certs | Local | Trying to copy cert pub"
  ansible.builtin.copy:
    dest: "{{ site.ssl.file_pub }}"
    src: "files/certs/{{ site.ssl.file_pub }}"
    mode: 0444
  ignore_errors: true
  register: copy_cert_pub
  when:
    - site.ssl.mode == 'local'
    - not exists_cert_pub.stat.exists
  tags: [certs, sites]

- name: "Nginx | Debian | Site {{ name }} | Certs | Local | Trying to copy cert pk"
  ansible.builtin.copy:
    dest: "{{ site.ssl.file_key }}"
    src: "files/certs/{{ site.ssl.file_key }}"
    mode: 0444  # since owner is not possible on 'nobody'
  no_log: true
  register: copy_cert_key
  ignore_errors: true
  when:
    - site.ssl.mode == 'local'
    - copy_cert_pub.failed is undefined or not copy_cert_pub.failed
    - not exists_cert_key.stat.exists
  tags: [certs, sites]
