---

- name: Nginx | Debian | Showing debug info - user provided config
  ansible.builtin.debug:
    var: nginx
  when: debug | bool

- name: Nginx | Debian | Showing debug info - running config
  ansible.builtin.debug:
    var: NGINX_CONFIG
  when: debug | bool

- name: Nginx | Debian | Installing nginx
  ansible.builtin.apt:
    pkg: "{{ NGINX_HC.packages }}"
    state: present
    update_cache: true
  tags: [base]

- name: Nginx | Debian | Creating service user
  ansible.builtin.user:
    name: "{{ NGINX_CONFIG.user }}"
    shell: '/usr/sbin/nologin'
    comment: 'Nginx Service User'

- name: Nginx | Debian | Setting base config
  ansible.builtin.lineinfile:
    path: '/etc/nginx/nginx.conf'
    regexp: "{{ item.search }}"
    line: "{{ item.replace }}"
    validate: "nginx -t -c %s"
    insertafter: "{{ item.after | default(omit) }}"
    backrefs: true
  register: nginx_user_update_raw
  loop: "{{ NGINX_HC.main_config }}"

# todo: implement GeoIP
#   https://fedingo.com/how-to-block-ip-by-country-in-nginx/

- name: Nginx | Debian | Restarting nginx
  ansible.builtin.systemd:
    name: 'nginx.service'
    state: restarted
  when: nginx_user_update_raw.changed

- name: Nginx | Debian | Removing default site
  ansible.builtin.file:
    path: '/etc/nginx/sites-enabled/default'
    state: absent

- name: Nginx | Debian | Removing status page
  ansible.builtin.include_tasks: rm_status.yml
  when: NGINX_CONFIG.status_page.state != 'present'
  tags: [base, config, sites]
  args:
    apply:
      tags: [base, config, sites]

- name: Nginx | Debian | Processing sites
  ansible.builtin.import_tasks: sites.yml

- name: Nginx | Debian | Starting/Enabling nginx
  ansible.builtin.systemd:
    name: 'nginx.service'
    enabled: yes
    state: started
  tags: [base]

- name: Nginx | Debian | Restarting nginx  # reload will not enable all config changes.. we could check for changes in the future
  ansible.builtin.systemd:
    name: 'nginx.service'
    state: restarted
  tags: [base, config, sites, certs]
  changed_when: false
