---

- name: Nginx | Debian | Installing nginx
  ansible.builtin.apt:
    pkg: ['nginx']

- name: Nginx | Debian | Configuring certificates
  ansible.builtin.import_tasks: debian/certs.yml

- name: Nginx | Debian | Adding site config
  ansible.builtin.template:
    src: 'templates/etc/nginx/sites-available/site.j2'
    dest: "/etc/nginx/sites-available/site_{{ NGINX_DOMAIN }}"
  register: site_config

- name: Nginx | Debian | Enabling site config
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/site_{{ NGINX_DOMAIN }}"
    dest: "/etc/nginx/sites-enabled/site_{{ NGINX_DOMAIN }}"
    state: link
  register: site_state

- name: Nginx | Debian | Enabling nginx service
  ansible.builtin.systemd:
    name: 'nginx.service'
    enabled: yes
    state: started

- name: Nginx | Debian | Restarting nginx service
  ansible.builtin.systemd:
    name: 'nginx.service'
    state: restarted
  when: site_config.changed or site_state.changed
