---

- name: "Nginx | Remove Site '{{ name }}' | Removing config"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/nginx/sites-enabled/site_{{ name }}"
    - "/etc/nginx/sites-available/site_{{ name }}"
  notify: restart-nginx

- name: "Nginx | Remove Site '{{ name }}' | Removing local certificates"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ NGINX_CONFIG.ssl.path }}/{{ name }}.crt"
    - "{{ NGINX_CONFIG.ssl.path }}/{{ name }}.key"
    - "{{ NGINX_CONFIG.ssl.path }}/{{ name }}.csr"
  when: "site.ssl.mode in ['selfsigned', 'existing', 'ca']"

- name: "Nginx | Remove Site '{{ name }}' | | Removing basic-auth files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/nginx/auth/auth_{{ name }}"
    - "/etc/pam.d/nginx_{{ name }}_system"
    - "/etc/pam.d/nginx_{{ name }}_custom"
