---

- name: "Nginx | Debian | Remove Site '{{ name }}' | Removing config"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  register: site_config
  loop:
    - "/etc/nginx/sites-enabled/site_{{ name }}"
    - "/etc/nginx/sites-available/site_{{ name }}"

- name: "Nginx | Debian | Remove Site '{{ name }}' | Removing local certificates"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ NGINX_CONFIG.ssl.path }}/{{ name }}.crt"
    - "{{ NGINX_CONFIG.ssl.path }}/{{ name }}.key"
    - "{{ NGINX_CONFIG.ssl.path }}/{{ name }}.csr"
  when: "site.ssl.mode in ['selfsigned', 'existing', 'ca']"

- name: "Nginx | Debian | Remove Site '{{ name }}' | Restarting nginx service"
  ansible.builtin.systemd:
    name: 'nginx.service'
    state: restarted
  when: site_config.changed
